### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by SamuelAlev** [Mavhod/GodotGPS#2]
Hello,
I'm trying to use the admob module ([https://github.com/jlopezcur/GodotAdmob](url)) with this one.
(If I try this one or the other alone, it work)
I remove the meta-data from the admob module:

```
  <meta-data android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
```

And I get:

```:transformClassesWithDexForDebug FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task :'transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: 
com.android.ide.common.process.ProcessException:
java.util.concurrent.ExecutionException: com.android.dex.DexException: 
Multiple dex files define Lcom/google/android/gms/internal/zzog;

**Comment by Mavhod** [comment]
I use https://github.com/Mavhod/GodotAdmob with delete meta-data in GodotGPS module
```
 <meta-data android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
```
and use last Godot update branch 2.1
I build all success and can run with admob and google play service fine.

**Comment by SamuelAlev** [comment]
And its work! 
Have you any plan to add Interstitial to your admob module ?

**Comment by Mavhod** [comment]
Seem many people use admob module, so yes I cloud add Interstitial.
Today I dev game project for PC platform, but maybe I will do it.
Maybe I see other fellow godot module for this work :P.
